### PR TITLE
Added displayEventTimes properties whether need to show the times are not. Modified in the tooltip and also in slide box.

### PR DESCRIPTION
**Pull request by jeevasusej**

### CODE REVIEW

**Comment by bergera** [comment]
:+1: My use case doesn't deal with times at all, very useful.

**Comment by mattlewis92** [comment]
Sorry about the late reply with this, I've opted instead to abstract all the logic into the `calendarEventTitle` service where you can override it's methods and customise how event titles get displayed which should be much more flexible and fit more use cases.

e.g. 

```
calendarEventTitle.monthViewTooltip = function(event) {
  return event.title; // no time will be displayed on the month view tooltip now
}
```

Hope this helps! 😄

**Comment by Jeevanandanj** [comment]
Thank you :-).. But  I didn't try.

Can we use this to hide time in slide box?

**Comment by mattlewis92** [comment]
Yup you just need to override this method like so (this is only in master, I've not yet cut a new version yet as there's still a few issues to sort out first)
```
calendarEventTitle.monthViewTooltip = function(event) {
  return event.title; // no time will be displayed on the month view now
}
```

**Comment by gsrdatta** [comment]
Where should i override the method ?..(new to angularjs)

**Comment by jeevasusej** [comment]
Superb plugin. Updated plugin works greatly.

**Pull request closed without merging**
