### PR TITLE
select-range

### PR DESCRIPTION
**Pull request by ChipsetSV**
Added select range hours on the day view.

### CODE REVIEW

**Comment by mattlewis92** [comment]
Hi this looks like a great PR, thanks for the contribution! I don't have the time to review this properly right now, but I can see the value in adding the functionality and will definitely accept it. Will try and find the time on the weekend to go over it.

**Comment by ChipsetSV** [comment]
Hello.
Thanks. I hope that all will be good )

**Comment by mattlewis92** [comment]
Just a couple things off the top of my head:
- [ ] remove the version bump, changelog and dist files from the PR as they'll get auto built on the next release
- [ ] remove the extra eslint rules as they're already set by the parent config the eslint file extends
- [ ] you can remove the `calendarConfig.selectRangeEnabled` option, and instead mark onSelectRange as an optional dependency like this: `onSelectRange: '&?', and then just check if the `onSelectRange` callback exists on not i.e. if `on-select-range` is not set then `vm.onSelectRange` will be undefined.

**Comment by ChipsetSV** [comment]
Ok. Agree with you.
Removing selectRangeEnabled from config - is a good idea.

**Comment by mattlewis92** [comment]
That looks much better now, thanks! Will check it out locally and play with it on the weekend, but pending that it looks good to merge :)

**Comment by mattlewis92** [comment]
Sorry about the delay with this, I finally got time to reviewing it. I've made a few small API changes for consistency with the rest of the module, refactored the DOM logic into it's own directive and added some tests. Thanks again for the contribution!

**Comment by ChipsetSV** [comment]
Ok. Thanks )

**Pull request merged**
