### PR TITLE
feat(excluded-days): Allow users to specify a set of days to be excluded from month and week view

### PR DESCRIPTION
**Pull request by santam85**
Taking inspiration from #570, I modified the directives to add an "excluded-days" attribute, that allows the user to specify which weekdays to include in month and week views.
Date modifier also supports it for day view, optionally skipping some days while navigating.

### CODE REVIEW

**Comment by mattlewis92** [comment]
This is absolutely perfect, nice job! I just want to clone it first and physically play around with it, but I will try and merge it asap 👍

**Comment by santam85** [comment]
@mattlewis92 thanks! I am working on improving the coverage for those lines I added to the dateModifier, might want to wait for that!

**Comment by santam85** [comment]
@mattlewis92 All done!

**Comment by santam85** [comment]
@mattlewis92 I guessed I rushed it a bit too much...
The resizing and dragging issue was because of the fact that the column size is now dynamic based on the number of days, and it was caused by the ng-class on the weekview template. By moving the calculations on the entire row, the elementDimensions directive triggers just once, so it's also a nice improvement now. I tried to keep template changes to a minimum otherwise.

**Comment by santam85** [comment]
@mattlewis92 I performed the required changes, looks like the bugs are gone. Have a look when you have time! Let me know if there are other changes required...

**Comment by mattlewis92** [comment]
@santam85 sorry about the late reply on this, been super busy with work and real life lately, not had much time for open source. I've just spotted a regression in the year view, would you mind taking a look when you have a sec? Thanks!

With this PR:
screen shot 2017-08-28 at 14 28 36
Master:
screen shot 2017-08-28 at 14 28 27

**Comment by santam85** [comment]
@mattlewis92 no worries, I was just a bit impatient to use the new feature on my project! Will have a look ASAP!

**Comment by igler** [comment]
I'd love to see this in master-branch as I need this feature in one of my projects. Any chance to release this in the near future?

**Comment by mattlewis92** [comment]
@igler it's just pending https://github.com/mattlewis92/angular-bootstrap-calendar/pull/640#issuecomment-325353749 to be fixed, you can point your bower / npm to the branch though if you want to use it today

**Comment by igler** [comment]
You mean the development branch?

**Comment by mattlewis92** [comment]
Sorry I meant the fork that this PR is based on: `santam85/angular-bootstrap-calendar#feature/excluded-days`

**Comment by santam85** [comment]
@mattlewis92 regression fixed, did you find anything else?

**Comment by mattlewis92** [comment]
I think that was it, I'm AFK today, but will try and get this merged tomorrow. Thanks a lot for your contribution! 😀

**Comment by santam85** [comment]
@mattlewis92 I'm sorry to bother you, but any news on this?

**Comment by mattlewis92** [comment]
Oops, sorry I completely forgot about this. I have just published this branch to npm as `0.30.0-beta.0`, I'm just going to test it on our app at work to make sure there are no major regressions and then I'll merge it and release properly 😄

**Comment by mattlewis92** [comment]
Published as `0.30.0`, thanks for your patience on this 👍

**Pull request merged**
