### PR TITLE
format for weekday labels on month view

### PR DESCRIPTION
**Pull request by simpixelated**
Added an attribute to the main directive: `calendar-day-label-format`, which allows the user to specify 'dd', 'ddd', or any other moment format. In the helper I switched from Angular's date $filter to moment's format() because it offers way more flexibility: http://momentjs.com/docs/#/displaying/format/

The rest of the calls to getWeekDayNames already pass `false`, which will use the default 'dddd' format (same as Angular's 'EEEE').

For example, I want to display 'S', 'M', 'T', etc. for my weekdays on top of the month view calendar. I can set `calendar-day-label-format="dd"`, then globally override moment's `weekdaysMin` to just the first letter:

```javascript
moment.locale('en', {
    weekdaysMin : ["S", "M", "T", "W", "T", "F", "S"]
});
```

### CODE REVIEW

**Comment by mattlewis92** [comment]
Hi, thanks for the pull request. 

I think the default behaviour should be to fallback to using angular's date filter if no value is set, this would preserve backwards compatibility and avoid users having to load moment's locale files as well as angular's.

For the sake of completeness I would suggest adding it to the week view and add a similar option for the year view as well.

I'll happily make these changes myself on the weekend or feel free to send an updated PR :)

**Comment by simpixelated** [comment]
With this implementation, don't you only need to load moment's locale files if you're providing another translation on top of 'en'? Anyway, the reason I choose to use moment().format() instead of angular's date filter is that allows me to use custom day names, plus all of moment's day formatting options. With Angular, you only have the options of EEE or EEEE --- which you had already accounted for with the short = true/false param.

Thanks for the feedback. I figured I might have to maintain a fork in order to make the tweaks I need for a specific implementation, but I thought I'd make them generic enough for you to use, if you so choose.

**Comment by mattlewis92** [comment]
https://github.com/mattlewis92/angular-bootstrap-calendar/issues/43 was asking for something similar. So I've made all date formats configurable in a provider. You can use it like this:
```
calendarConfigProvider.configureDateFormats({
  weekDay: 'dd'
});
```

This should satisfy your use case :)

**Comment by shivavelingker** [comment]
@mattlewis92 Does this still work? I couldn't seem to use that code or the issue you referenced to achieve the single character weekday abbreviation.

**Pull request closed without merging**
