### PR TITLE
Title of the calendar

### PR DESCRIPTION
**Pull request by marcoos13**
Hey, there awesome work!

I have a question about the title of the calendar in week display for example:
See the attach image.
image
Is there a way to change the format into a different one like:
2017 Apr, 9-15
Instead of:
Week 16 of 2017

Thank you,
Cheers:)

### CODE REVIEW

**Comment by mattlewis92** [comment]
You need to override the `calendarTitle.week` function like so:
```
angular
  .module('myApp', [])
  .run(function(calendarConfig) {
    calendarConfig.week = function(viewDate) {
      // Use moment to format the date as you require: https://momentjs.com/docs/#/displaying/
    };
  })
```

Hope that helps! 😄

**Comment by marcoos13** [comment]
Hey mattlewis92, Thank you for your quick response!

I tried what you mentioned here, but for some reason, It never reaches the function:
image

**Comment by mattlewis92** [comment]
Sorry wrong service, it should be `calendarTitle` not `calendarConfig`

**Comment by marcoos13** [comment]
Thank you very much I really appreciate that :)

**Pull request closed without merging**
