### PR TITLE
fix(dayView): allow the day-view-event-chunk-size to be set to a custom size

### PR DESCRIPTION
**Pull request by bwobbones**
Part of an overall change to allow manual resizing of hour-parts (broken out from #620).

Currently the size of the hour parts is hard coded to 30.

This change allows the user to change this default (see the code in the examples provided) by exposing the usage of the `vm.dayViewEventChunkSize` variable to a `day-view-event-chunk-size` attribute on the `mwl-calendar` directive.

I tried to break this up further @mattlewis92, but could only extract the interact part because this `dayViewEventChunkSize` flows right though the code.

### CODE REVIEW

**Review by mattlewis92 — CHANGES_REQUESTED** [review]
I'm not sure `day-view-event-chunk-size` is the right option to use here, [the intent of that option](https://github.com/mattlewis92/angular-bootstrap-calendar#day-view-event-chunk-size) is to control the snap size of events. Can you create a new option called something like `day-view-segment-size` instead? Otherwise LGTM!

**Comment by jmsunseri** [comment]
Took me a bit to re-implement this with a new value called day-view-segment-size in my code and it seems to work but I also had to modify the css to match.  Was that not intended?

`.cal-day-box .cal-day-hour-part {
    height: 25px;
}`

**Comment by bwobbones** [comment]
Thanks for merging #651, i'll get time over the xmas break to look at the changes for this one.

@jmsunseri, I think you're right, I also had to change the css.  I'll add something to the README for it.

**Review by mattlewis92 — APPROVED** [review]

**Comment by mattlewis92** [comment]
LGTM, thanks for your contribution! Will cut a new release shortly 😄

**Comment by bwobbones** [comment]
thanks @mattlewis92!

**Pull request merged**
