### PR TITLE
day view displays all hours of the day instead of 6-10

### PR DESCRIPTION
**Pull request by joshsadler**
🙌

### CODE REVIEW

**Comment by mattlewis92** [comment]
I'd rather it be configurable like the original calendar, rather than hard coded. Sorry about the delay with doing this myself, but I'm busy 24/7 with a large project at work at the moment.

**Comment by joshsadler** [comment]
Since it's currently hardcoded it seemed more logical to include all hours rather than just a subset. I agree that a configurable option in the long run.

**Comment by mattlewis92** [comment]
Yeah you're right, I'll make it configurable next time I get an evening free.

**Comment by joshsadler** [comment]
Thanks for being you. ;)

**Pull request merged**
