### PR TITLE
feat(WeekView): Added height for events on week view

### PR DESCRIPTION
**Pull request by Gonah**
Added height for events when time is shown on the week view.

### CODE REVIEW

**Comment by Gonah** [comment]
I might need multi-day soon. I'll look into updating this once I have a better idea of my use case.

**Comment by wedow** [comment]
Is this pull request intended to solve #294 or something else? I can't seem to be able to build from source to test. If so, please let me know if there's anything I can do to help get this out.

**Comment by burtek** [comment]
#294 and many similar. Still waiting for the results though...

**Comment by spotlight2001** [comment]
will this be fixed?

by regarding the date, this  pull request looks abandoned

**Pull request closed without merging**
